name: gamificacao_dm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Splash Screen
  flutter_native_splash: ^2.3.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  
  # Interface e widgets
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Navegação
  go_router: ^12.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuração do Flutter Native Splash

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/